import type { Flight } from "./types"

const now = Date.now()
const inMin = (m: number) => new Date(now + m * 60_000).toISOString()

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: "OK001",
    number: "OK 645",
    airlineName: "Czech Airlines",
    airlineIata: "OK",
    direction: "departure",
    counterpart: { name: "Paris Charles de Gaulle", iata: "CDG", city: "Paris", countryCode: "FR" },
    scheduledTime: inMin(30),
    status: "Boarding",
    terminal: "2",
    gate: "B7",
    aircraftModel: "Airbus A319",
  },
  {
    id: "LH002",
    number: "LH 1397",
    airlineName: "Lufthansa",
    airlineIata: "LH",
    direction: "departure",
    counterpart: { name: "Frankfurt", iata: "FRA", city: "Frankfurt", countryCode: "DE" },
    scheduledTime: inMin(55),
    status: "Scheduled",
    terminal: "2",
    gate: "A4",
    aircraftModel: "Airbus A320",
  },
  {
    id: "FR003",
    number: "FR 2453",
    airlineName: "Ryanair",
    airlineIata: "FR",
    direction: "departure",
    counterpart: { name: "London Stansted", iata: "STN", city: "London", countryCode: "GB" },
    scheduledTime: inMin(85),
    actualTime: inMin(120),
    status: "Delayed",
    terminal: "1",
    gate: "C2",
    aircraftModel: "Boeing 737-800",
  },
  {
    id: "QS004",
    number: "QS 1207",
    airlineName: "SmartWings",
    airlineIata: "QS",
    direction: "departure",
    counterpart: { name: "Antalya", iata: "AYT", city: "Antalya", countryCode: "TR" },
    scheduledTime: inMin(150),
    status: "Cancelled",
    terminal: "1",
    aircraftModel: "Boeing 737 MAX 8",
  },
  {
    id: "AF101",
    number: "AF 1882",
    airlineName: "Air France",
    airlineIata: "AF",
    direction: "arrival",
    counterpart: { name: "Paris Charles de Gaulle", iata: "CDG", city: "Paris", countryCode: "FR" },
    scheduledTime: inMin(15),
    status: "EnRoute",
    terminal: "2",
    aircraftModel: "Airbus A220-300",
  },
  {
    id: "KL102",
    number: "KL 1357",
    airlineName: "KLM",
    airlineIata: "KL",
    direction: "arrival",
    counterpart: { name: "Amsterdam Schiphol", iata: "AMS", city: "Amsterdam", countryCode: "NL" },
    scheduledTime: inMin(40),
    status: "Scheduled",
    terminal: "2",
    aircraftModel: "Embraer 175",
  },
  {
    id: "TK103",
    number: "TK 1769",
    airlineName: "Turkish Airlines",
    airlineIata: "TK",
    direction: "arrival",
    counterpart: { name: "Istanbul", iata: "IST", city: "Istanbul", countryCode: "TR" },
    scheduledTime: inMin(-10),
    actualTime: inMin(-5),
    status: "Arrived",
    terminal: "1",
    aircraftModel: "Airbus A321neo",
  },
  {
    id: "EW104",
    number: "EW 6045",
    airlineName: "Eurowings",
    airlineIata: "EW",
    direction: "arrival",
    counterpart: { name: "Düsseldorf", iata: "DUS", city: "Düsseldorf", countryCode: "DE" },
    scheduledTime: inMin(70),
    actualTime: inMin(95),
    status: "Delayed",
    terminal: "2",
    aircraftModel: "Airbus A319",
  },
]
